"""Generate results registry for the paper from a completed run's metrics.json.

Never hand-typed numbers: emit LaTeX macros + results.tex that main.tex includes.
"""
from __future__ import annotations

import json
import os
from typing import Any, Dict


MACRO_HEADER = "% Auto-generated by gcl.report — do not hand-edit"


def _fmt(x: float, nd: int = 3) -> str:
    return f"{x:.{nd}f}"


def _sign(x: float, nd: int = 3) -> str:
    return f"{x:+.{nd}f}"


def _macro(name: str, value: str) -> str:
    return f"\\newcommand{{\\{name}}}{{{value}}}"


def write_results_tex(metrics_path: str, out_tex: str) -> Dict[str, Any]:
    with open(metrics_path) as f:
        m = json.load(f)
    learners = m["learners"]
    lines = [MACRO_HEADER, ""]
    blocks = []

    for name, d in learners.items():
        r = d["report"]
        safe = name.replace("_", "")
        lines.append(f"% --- learner: {name} ---")
        lines.append(_macro(f"{safe}acc", _fmt(r["acc"])))
        lines.append(_macro(f"{safe}bwt", _sign(r["bwt"])))
        lines.append(_macro(f"{safe}fwt", _sign(r["fwt"])))
        lines.append(_macro(f"{safe}forget", _fmt(r["forgetting"])))
        lines.append(_macro(f"{safe}auc", _fmt(r["auc"])))
        lines.append(_macro(f"{safe}stab", _fmt(r["stability"])))
        lines.append(_macro(f"{safe}updates", str(d["updates"])))
        lines.append(_macro(f"{safe}rollbacks", str(d["rollbacks"])))
        lines.append(_macro(f"{safe}frontier", _sign(d["frontier_score"])))
        lines.append("")

    canary = m.get("canary", {})
    lines.append(_macro("canaryOverlap", str(canary.get("overlap", "?"))))
    lines.append(_macro("canaryClean", "yes" if canary.get("clean") else "NO"))
    lines.append(_macro("streamHash", canary.get("stream_hash", "")))
    cfg = m.get("config", {})
    lines.append(_macro("modelName", cfg.get("model_name", "")))
    lines.append(_macro("loraRank", str(cfg.get("lora_r", ""))))
    lines.append(_macro("maxUpdates", str(cfg.get("max_updates", ""))))

    with open(out_tex, "w") as f:
        f.write("\n".join(lines))
    return {"written": out_tex, "learners": list(learners.keys()), "canary_clean": canary.get("clean", False)}


def main():
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("--run", required=True, help="run dir containing metrics.json")
    ap.add_argument("--out", required=True, help="output .tex file for the paper")
    args = ap.parse_args()
    res = write_results_tex(os.path.join(args.run, "metrics.json"), args.out)
    print("results.tex written:", json.dumps(res))


if __name__ == "__main__":
    main()
